package commands.toys;
import java.util.Random;

import commands.Command;
import net.dv8tion.jda.core.events.message.guild.GuildMessageReceivedEvent;

public class Jokes extends Command
{
	@Override
	public void run(GuildMessageReceivedEvent msgEvent, String... parameters)
	{
		String[] Jokes = new String[] { "If you understand English, press 1. If you do not understand English, press 2.",
				"I'm employed at a computer security company and have a colleague whose name is M. Alware." + "\n" + "His e-mail address is malware@company.com.",
				"I put so much more effort into naming my first Wi-Fi than my first child.",
				"The cool part about naming your kid is you don't have to add six numbers to make sure the name is available.",
				"What's the Boogeyman's part time job?" + "\n" + "BoogeyNAN!",
				"I hate audio correct.",
				"My girlfriend and I often laugh about how competitive we are." + "\n" + "But I laugh more.",
				"Q: What kind of exercise do lazy people do?" + "\n" + "A: Diddly-squats.",
				"What's the difference between a hippo and a Zippo? Ones really heavy and the others a little lighter.",
				"Why did the chicken cross the road?" + "\n" + "Hey, you keep coming up with new material.",
				"There are these two beautiful marble statues on either side of a big open piazza. For centuries they have stood frozen, starring longingly into each other's eyes." + "\n" + "One day the gods look down upon them with pity and decide to grant them one hour of mortal life. The statues, overwhelmed with joy, rush across the square and into each others arms and immediately run off into a bush to fulfill their greatest desires." + "\n" + "After about a half an hour of rustling around in the bushes they emerge, panting and sweaty." + "\n" + "\"Wow\" says the one statue, \"that was amazing\" \"A dream come true\" says the other \"but we've got a half an hour left, what should we do now?\" \"I know\" the first responds \"this time I'll hold the pigeon down while you poo on it\"",
				"A farmer and his dog are herding sheep. They finish and his dog says \"I counted 40 sheep\". The farmer replies, \"That's odd I only got 37\". The dog replies \"I rounded them up\".",
				"Three engineers are on a road trip, a mechanical engineer, and electrical engineer, and a software engineer. They pull over at a restaurant to eat and when they try to leave, the car won't start." + "\n" + "The mechanical engineer says \"Let me check the starter.\"" + "\n" + "The electrical engineer says \"Let me make sure the battery is connected. Always try the easiest solutions first.\"" + "\n" + "The software engineer rolls his eyes and says \"Before we do anything else, let's all just get out of the car and then get back in.\"",
				"A Spanish magician says he will disappear on the count of 3. He says \"uno, dos...\" poof. He disappeared without a tres.",
				"A man walks into a library and asked if they had any books about paranoia." + "\n" + "Librarian: \"They're right behind you!\".",
				"I once bought some used paint. It was in the shape of a house.",
				"The other day, my wife asked me to pass her lipstick but I accidentally passed her a glue stick. She still isn't talking to me.",
				"I've been told I'm condescending." + "\n" + "(that means I talk down to people)",
				"When you look really closely, all mirrors look like eyeballs.",
				"Guy walks into a bar and orders a fruit punch." + "\n" + "Bartender says \"Pal, if you want a punch you'll have to stand in line\"" + "\n" + "Guy looks around, but there is no punch line.",
				"What do you get when you cross a cow and an octopus?" + "\n" + "A call from the ethics committee and immediate revocation of your grant funding.",
				"What's the difference between a good joke and a bad joke timing.",
				"Why don't ants get sick?" + "\n" + "Because they have little antybodies.",
				"Before your criticize someone, walk a mile in their shoes. That way, when you do criticize them, you're a mile away and have their shoes.",
				"My friend says to me: \"What rhymes with orange\"" + "\n" + "I said: \"No, it doesn't.\"",
				"I went bobsleighing the other day, took out 250 bobs",
				"What did the pirate say when he turned 80 years old?" + "\n" + "Aye matey!",
				"My husband told me I had to stop acting like a flamingo. So I had to put my foot down.",
				"I couldn't figure out why the baseball kept getting larger. Then it hit me.",
				"This is my step ladder. I never knew my real ladder.",
				"I bought my friend an elephant for his room." + "\n" + "He said: Thanks." + "\n" + "I said: Don't mention it.",
				"A man walks into a bar with a giraffe. They both get pissed. The giraffe falls over. The man goes to leave and the bartender says, \"Oi. You can't leave that lyin' there.\" And the man says, \"No. It's not a lion. It's a giraffe.\"",
				"Did you hear about the antennas that got married? The ceremony was okay but the reception was amazing.",
				"Two fish are in a tank. One looks to the other and says, \"You man the guns, I'll drive!\"",
				"What's the difference between a well dressed man on a unicycle and a poorly dressed man on a bicycle?" + "\n" + "Attire",
				"An **infinite** number of mathematicians walk into a bar. Bartender asks, \"what can I get you guys\"?" + "\n" + "First mathematician says \"I'd like a pint of beer please.\" The second one says \"I just want a half pint.\" The third one says \"a quarter pint\". The bartender listens for a while and then stops them." + "\n" + "He pours out two pints and says \"you know, you guys really ought to know your limits.\"",
				"Bees?",
				"Oh hey, I have a great knock knock joke, but you have to start it.",
				"Did you know diarrhea is hereditary? It runs through your jeans.",
				"What did the cannibal do after he dumped his girlfriend?" + "\n" + "Wiped his arse.",
				"My dog used to chase people on a bike a lot. It got so bad, finally I had to take his bike away.",
				"In a boomerang shop: \"I'd like to buy a new boomerang please. Also, can you tell me how to throw the old one away?\"",
				"I can't believe I forgot to go to the gym today. That's 7 years in a row now.",
				"I thought I'd tell you a good time travel joke ' but you didn't like it.",
				"I heard a report about a bad outbreak of the tummy bug, apparently 9 out of 10 people there suffered from diarrhea. I can't stop thinking about that tenth person who apparently enjoyed it.",
				"They threw me out of the cinema today for bringing my own food. But come on ' the prices are way too high, plus I haven't had a barbecue in months.",
				"Why haven't you ever seen any elephants hiding up trees? Because they're really, really good at it.",
				"We have a strange custom in our office. The food has names there. Yesterday for example I got me a sandwich out of the fridge and its name was \"Michael\".",
				"I really don't know which kid I'm supposedly being unfair to, according to my wife. Thomas, Anton, or the fat, ugly one?",
				"Why did the physics teacher break up with the biology teacher? There was no chemistry.",
				"I got another letter from this lawyer today. It said 'Final Notice'. Good that he will not bother me anymore.",
				"Don't be sad when a bird craps on your head. Be happy that dogs can't fly.",
				"I went on a date with a chess player to an Italian restaurant. With checkered table cloths. It took him maybe half an hour to pass the salt.",
				"I'll never buy a vacuum cleaner. It would only just gather dust.",
				"Time is money. Therefore, ATMs are time machines.",
				"Tomato is a fruit, right? Does that make ketchup a smoothie?",
				"I dated a tennis player but I'll never make such a mistake again. Love has zero meaning to them.",
				"How many believers in telekinesis here? Raise that guy's hand.",
				"Artificial intelligence is very impressive but it's got nothing on natural idiocy.",
				"I got Pavlov in my exam but I couldn't remember who that that dude was. His name really didn't ring a bell.",
				"My friend wrote a book on polstergeists, it's simply flying off the shelves.",
				"The stationary shop moved. It really surprised me.",
				"'My career is in ruins.' ~Herbert Dillgrin, archaeologist",
				"I'm a pro at sleeping. I could do it with my eyes closed.",
				"Apple just posted on their Facebook page that their store got robbed. They're looking for iWitnesses.",
				"Here, I bought you a calendar. Your days are numbered now.",
				"Talk is cheap, yeah? Have you ever talked to a lawyer?!",
				"When everything's coming your way, perhaps you're in the wrong direction on the motorway?",
				"If I got 50 pence for every failed maths exam, I'd have '6.30 now.",
				"Do I lose when the police officer says papers and I say scissors?",
				"Famous last words of a postman: What a lovely dog you have!",
				"It's cleaning day today. I've already polished off a whole chocolate bar.",
				"You look so bad your mum got a penalty for littering when she dropped you off at school today.", 
				"I hate it when I run out of toilet paper and I have to make the trip to the grocery store in really small steps.",
				"A cannibal came home late to family dinner. He got the cold shoulder.",
				"A magician was driving down the road and turned into a shopping mall.",
				"I told my girlfriend she drew her eyebrows too high. She seemed surprised.",
				"And God said to John, come forth and you shall be granted eternal life." + "\n" + "But John came fifth and won a toaster." };
        Random r = new Random();
        msgEvent.getChannel().sendMessage(Jokes[r.nextInt(Jokes.length)]).queue();
	}
}
